import { writeFile } from 'node:fs/promises';
import { products } from '../src/data/products.js';
import { packages, brewTools } from '../src/data/collections.js';

// Hex UTF-8 literals avoid SQL quoting/SQL-mode differences for Thai text.
const sqlText = value => `CONVERT(0x${Buffer.from(String(value), 'utf8').toString('hex')} USING utf8mb4)`;
const literal = value => value === '' ? "''" : sqlText(value);
const price = value => {
  const number = Number(String(value).replaceAll(',', ''));
  if (!Number.isFinite(number) || number < 0) throw new Error('Invalid catalog price');
  return number.toFixed(2);
};
const entries = [
  ...products.map((p, i) => ({p, id:p.id || `matcha-${p.color || i + 1}`, category:'matcha'})),
  ...packages.map((p, i) => ({p, id:p.id || `package-${i + 1}`, category:'package'})),
  ...brewTools.map((p, i) => ({p, id:p.id || `tool-${i + 1}`, category:'tools'})),
];
const lines = [
  '-- Generated by node scripts/mysql-catalog.mjs from the current website catalog.',
  '-- Insert-only: rerunning does NOT overwrite prices/data edited in MySQL.',
  'USE matcha_mori;', 'START TRANSACTION;',
];
for (const {p,id,category} of entries) {
  lines.push(`INSERT INTO products(id,name,category,price,size,description,image_path,details) VALUES (${[
    literal(id),literal(p.name),literal(category),price(p.price),literal(p.size || ''),
    literal(p.description || p.detail || ''),literal(p.image || ''),literal(JSON.stringify(p)),
  ].join(',')}) ON DUPLICATE KEY UPDATE id=products.id;`);
}
for (const {p,id,category} of entries.filter(entry => entry.category === 'package')) {
  p.items.forEach((item, i) => {
    // Matcha has an unambiguous product reference. Accessory names/prices in the
    // source are inconsistent, so preserve snapshots until the owner reviews them.
    const matcha = item.isMatcha && entries.find(entry => entry.category === 'matcha' && entry.p.name === item.name);
    if (item.isMatcha && !matcha) throw new Error('Unknown package matcha');
    lines.push(`INSERT INTO package_items(package_id,position,product_id,name,unit_price,quantity,matcha_replaceable) VALUES (${literal(id)},${i + 1},${matcha ? literal(matcha.id) : 'NULL'},${literal(item.name)},${price(item.price)},1,${item.isMatcha ? 1 : 0}) ON DUPLICATE KEY UPDATE position=package_items.position;`);
  });
}
lines.push('COMMIT;');
await writeFile(new URL('../mysql/catalog.sql', import.meta.url), lines.join('\n') + '\n');
console.log(`Generated ${entries.length} products and ${packages.reduce((n,p)=>n+p.items.length,0)} package items.`);
